---
name: Make

on:
  schedule:
    - cron: '0 0 1 * *'
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  make:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      matrix:
        os:
          - windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup on Linux
        if: runner.os != 'Windows'
        shell: bash
        run: |
          bash '.github/workflows/make.sh' setup

      - name: Build on Linux
        if: runner.os != 'Windows'
        shell: bash
        run: |
          bash '.github/workflows/make.sh' build

      - name: Setup on Windows
        if: runner.os == 'Windows'
        uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          update: true
          install: mingw-w64-ucrt-x86_64-efl mingw-w64-ucrt-x86_64-rust mingw-w64-ucrt-x86_64-pkg-config mingw-w64-ucrt-x86_64-cargo-msrv

      - name: Build on Windows
        if: runner.os == 'Windows'
        shell: msys2 {0}
        run: |
          set -euo pipefail
          cargo clippy --quiet --features="all" --examples
          cargo build --release --features="all" --examples

